<?php 
  session_start(); 

  if (!isset($_SESSION['username'])) {
  	$_SESSION['msg'] = "You must log in first";
  	header('location: login.php');
  }
  if (isset($_GET['logout'])) {
  	session_destroy();
  	unset($_SESSION['username']);
  	header("location: login.php");
  }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Welcome, to Your Travel</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="yourtravelcss.css">
</head>
<body>
<div class="header">
  <h1>Welcome, to Your Travel</h1>
  <p>Travel <b>Your</b> way.</p>
      </div>

<div class="navbar">
        <a href="index.php" class="active">Home</a>
        <a href="review.php">Reviews/Ratings</a>
        <a href="destinationlandingpage.php">Destinations</a>
        <a href="suggestedforyou.php">Suggested for You</a>
        <a href="myaccount.php">My Account</a>
        <div style="text-align:right">
            <?php
            if (isset($_SESSION['username'])) {
                echo "<p>Welcome <strong><?php echo $_SESSION['username']; ?></strong></p>
                    <p> <a href="index.php?logout='1'" style="color: red;">logout</a> </p>";

            } else {
                    echo "<a href="registration.php" class="right">Sign up here!</a>
                        <a href="login.php" class="right">Login Here!</a>";
            }
            ?>
        </div>
</div>
<div class="clearfix">
<div class="column">
  <div class="side column">
    <h2>News/Updates</h2>
    <h5>Full website launching soon!</h5>
    <div><img src="webpage.png" alt="WebPage" style="height:200px;"></div>
    <p>Stay tuned for more new/updates!</p>
    <h3>More Stuff</h3>
    <p>Talk about more stuff here</p>
    <div class="fakeimg" style="height:60px;">some links to places</div><br>
    <div class="fakeimg" style="height:60px;">some links to places</div><br>
    <div class="fakeimg" style="height:60px;">some links to places</div>
  </div>
  <div class="content column">
    <h2>Welcome to Your Travel!</h2>
    <h5>Introduction, Jan 31, 2020</h5>

    <div><img src="beach.png" alt="Beach" width="1000" height="400"></div>
    <p>Let us tell you a little about us...</p>
    <p>Our website aims at trying to help our visitors with a very important issue that plagues many people. 
      Sometimes it is difficult to find the destination of your next vacation. 
      Our website makes finding information about the most popular travel locations and 
      even give you a suggestion generated by our state of the art algorithm.</p>
    <br>
    <h2>Today's Featured Destination.</h2>
    <h5>Featured Destination, Feb 1, 2020</h5>
    <div class="fakeimg" style="height:200px;">Image</div>
    <p>Title of the destination.</p>
    <p>Some info about the destination.</p>
  </div>
</div>
</div>

<div class="footer">
  <a href="aboutus.html">About Us</a>
  <a href="forum.html">Forums</a>
  <a href="contactus.html">Contact Us</a>
  <a href="reportabug.html">Report A Bug</a>
  <a href="careers.html">Careers</a>
</div>

</body>
</html>